services:
  api:
    build: ./backend
    container_name: gym_api_aws
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/gymdb
    depends_on:
      - mongo
    networks:
      - gym_net

  mongo:
    image: mongo:6
    container_name: gym_mongo_aws
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gym_net

volumes:
  mongo_data:

networks:
  gym_net:
    driver: bridge
